language: php
sudo: required
php:
  - 7.1
  - 7.2
  - 7.3
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
    - php: 7.3

before_install: sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] ; then echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ; fi'

before_script: composer install

script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] ; then ./vendor/bin/phpcs --standard=vendor/internations/kodierungsregelwerksammlung/ruleset.xml --exclude=InterNations.Syntax.MethodTypeHints ./src/ ; fi'
  - phpunit
